### ISSUE TITLE
AddressSanitizer reports stack usage after the scope in 

### ISSUE THREAD

**Issue by snikulov** [rbock/sqlpp11-connector-sqlite3#54]
**Description:**
AddressSanitizer reports stack usage after the scope

The issue was already fixed with #43 but restored with next change 2f57ec879ecc4570896d0328f8d1de4ea353ddad

**How to reproduce:**
Build sqlpp11-connector-sqlite3 with clang and -fsanitize=address

CC=clang CXX=clang++ cmake .. -DCMAKE_CXX_FLAGS="-g -fsanitize=address" -DHinnantDate_ROOT_DIR=~/work/github/3rdparty/date
make
make test

**Log**
================================
==29719==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffccda3c9a8 at pc 0x00000073955b bp 0x7ffccda3a1e0 sp 0x7ffccda3a1d8
3: READ of size 1 at 0x7ffccda3c9a8 thread T0
3:     #0 0x73955a in sqlpp::result_row_t<sqlpp::sqlite3::connection, sqlpp::field_spec_t<TabSample_::Alpha::_alias_t, sqlpp::integral, true, false>, sqlpp::field_spec_t<TabSample_::Beta::_alias_t, sqlpp::text, true, false>, sqlpp::field_spec_t<TabSample_::Gamma::_alias_t, sqlpp::boolean, false, false>, sqlpp::field_spec_t<sqlpp::max_alias_t::_alias_t, sqlpp::integral, true, false> >::operator bool() const /BUILDBOT/server/worker1/Centos7-clang5-x86_64/build/build.clang/../3rdparty/sqlpp11/include/sqlpp11/result_row.h:222:14
3:     #1 0x7315d0 in main /BUILDBOT/server/worker1/Centos7-clang5-x86_64/build/build.clang/../3rdparty/sqlpp11-connector-sqlite3/tests/SelectTest.cpp:161:19
3:     #2 0x7f0597afac04 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274
3:     #3 0x65e4dc in _start (/BUILDBOT/server/worker1/Centos7-clang5-x86_64/build/build.clang/3rdparty/sqlpp11-connector-sqlite3/bin/Sqlpp11Sqlite3SelectTest+0x65e4dc)
3: 
3: Address 0x7ffccda3c9a8 is located in stack of thread T0 at offset 10152 in frame
3:     #0 0x72e60f in main /BUILDBOT/server/worker1/Centos7-clang5-x86_64/build/build.clang/../3rdparty/sqlpp11-connector-sqlite3/tests/SelectTest.cpp:94

**Comment by snikulov** [comment]
@rbock I'll prepare PR for this today.
